## NumPy

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

#### Importing the Numpy library

In [1]:
import numpy as np 

#### Creating the NumPy array

In [5]:
# we can pass a list, tuple or any array-like object into array()
arr =  np.array([1, 2, 3, 4, 5])

# They can be:

#       0-D Arrays
arr0 = np.array(42)

#       1-D Arrays
arr1 = np.array([1, 2, 3, 4, 5])

#       2-D Arrays
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

#       3-D Arrays
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# prints the number 6
print(arr3[0][1][2])

# The attribute (shape) returns a tuple with each index having the number of corresponding element.
print(arr3.shape)


6
(2, 2, 3)


#### Copy() and View()

In [ ]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

# Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

# The attribute (base) refers to the original object ('None' if there isn't.)

#### Reshape

In [6]:
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

# 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

# The multiplication of the numbers (4,3) must be the same as the number of elements.

# If (-1), NumPy will calculate this number for you (equals 2)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

# We can also flat an array by using reshape(-1)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Iterating arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

# The number of loops is the same as the dim of the array.
# if there was only a for loop, the output would be:
[1, 2, 3]
[4, 5, 6]


#       The nditer() method can help handling with for iterations.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

# Enumerated Iteration Using ndenumerate()
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)
